---
- hosts: localhost
  connection: local
  gather_facts: True
  become: True
  roles:
    - role: users
    - role: utc-timezone
    - role: sar
    - role: banner
    - { role: teleport, teleport_role: 'auth' }